version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
    timezone: Africa/Cairo
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rxjs
    versions:
    - 6.6.4
    - 6.6.6
    - 6.6.7
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
